AY1920S1-CS2113T-W17-2/main

- src/main/java/Command.java
- src/main/java/Deadline.java
- src/main/java/Duke.java
- src/main/java/Event.java
- src/main/java/Storage.java
- src/main/java/Task.java
- src/main/java/TaskList.java
- src/main/java/Todo.java
- src/main/java/Ui.java
- src/test/java/DukeTest.java
- src/test/java/TaskListTest.java
Port code from Phase 1 of project.
> Porting code from Phase 1

- src/main/java/wallet/command/Command.java
- src/main/java/wallet/storage/Storage.java
- src/main/java/wallet/task/TaskList.java
- src/main/java/wallet/task/Tentative.java
Edited 4 class files and added a class file Tentative that extends Task. Symbol for Tentative is [?].
> B-TentativeScheduling

- duke.txt
- src/main/java/wallet/Duke.java
- src/main/java/wallet/command/Command.java
- src/main/java/wallet/storage/Storage.java
- src/main/java/wallet/task/DoWithinPeriod.java
- src/main/java/wallet/task/TaskList.java
- src/main/java/wallet/ui/Reminder.java
Not scaled to actual Record Class and sub classes yet
> B-DoWithinPeriodTasks and B-Reminders

- build.gradle
- src/main/java/wallet/command/Command.java
- src/main/java/wallet/storage/Storage.java
- src/main/java/wallet/task/TaskList.java
- src/main/java/wallet/task/Tentative.java
Add functionality to package app into jar file. 
- Run "gradlew shadowJar" in cmd in main folder
- jar file created under ./build/libs
- open cmd in ./build/libs and run java -jar {jarName}
- if want new version, update  archiveVersion under shadowJar in build.gradle
> [CS2113T-W17-2]-Xdecosee-A-Jar

- src/main/java/wallet/Main.java
- src/main/java/wallet/command/Command.java
- src/main/java/wallet/record/Expense.java
- src/main/java/wallet/record/ExpenseList.java
- src/main/java/wallet/record/ExpenseParser.java
- src/main/java/wallet/record/Loan.java
- src/main/java/wallet/record/Record.java
- src/main/java/wallet/task/ScheduleList.java
- src/test/java/wallet/record/ExpenseListTest.java
- src/test/java/wallet/record/ExpenseParserTest.java
Allow users to add and view recurring expense records.
> [CS2113T-W17-2]-kyang96-B-RecurringTasks

- build.gradle
- config/checkstyle/checkstyle.xml
- duke.txt
- src/main/java/wallet/Main.java
- src/main/java/wallet/command/Command.java
- src/main/java/wallet/contact/Contact.java
- src/main/java/wallet/contact/ContactList.java
- src/main/java/wallet/record/Contact.java
- src/main/java/wallet/record/Expense.java
- src/main/java/wallet/record/Loan.java
- src/main/java/wallet/record/Notes.java
- src/main/java/wallet/record/Record.java
- src/main/java/wallet/record/RecordList.java
- src/main/java/wallet/storage/Storage.java
- src/main/java/wallet/task/Deadline.java
- src/main/java/wallet/task/DoWithinPeriod.java
- src/main/java/wallet/task/Event.java
- src/main/java/wallet/task/ScheduleList.java
- src/main/java/wallet/task/Task.java
- src/main/java/wallet/task/TaskList.java
- src/main/java/wallet/task/Tentative.java
- src/main/java/wallet/task/Todo.java
- src/main/java/wallet/ui/MyThread.java
- src/main/java/wallet/ui/Reminder.java
- src/main/java/wallet/ui/Ui.java
- src/test/java/wallet/DukeTest.java
- src/test/java/wallet/task/TaskListTest.java
Added checkstyles to gradle and fixed checkstyle issues
> Checkstyle

- docs/UserGuide.adoc
User-Guide adoc
Converted our Google docs User Guide text version to adoc version
> Added User-Guide 

- src/main/java/wallet/logic/command/EditCommand.java
- src/main/java/wallet/logic/parser/ParserManager.java
- src/main/java/wallet/model/record/ExpenseList.java
- src/test/java/wallet/logic/command/DeleteCommandTest.java
- src/test/java/wallet/logic/command/EditCommandTest.java
- src/test/java/wallet/logic/parser/EditCommandParserTest.java
- src/test/java/wallet/model/record/ExpenseListTest.java
- src/test/java/wallet/model/record/ExpenseParserTest.java
Added JUnit testing code for DeleteCommand, EditCommand and EditCommandParser classes.
> Added testing for DeleteCommand, EditCommand and EditCommandParser classes.

- src/main/java/wallet/Main.java
- src/main/java/wallet/logic/LogicManager.java
- src/main/java/wallet/logic/command/ReminderCommand.java
- src/main/java/wallet/logic/parser/ParserManager.java
- src/main/java/wallet/logic/parser/ReminderCommandParser.java
- src/main/java/wallet/ui/MyThread.java
- src/main/java/wallet/ui/Reminder.java
Added: RemindCommand and ReminderCommandParser class
Added: Java docs to ReminderCommandParser
> Reminder Commands done

- src/main/java/wallet/logic/command/ListCommand.java
- src/main/java/wallet/ui/Ui.java
Improved UI when listing expenses.
> Updated UI for listing expenses.

- src/main/java/wallet/logic/LogicManager.java
- src/main/java/wallet/logic/parser/ParserManager.java
- src/main/java/wallet/storage/HelpStorage.java
ParserManager
1. return null if command not found
Logic Manager
1. Prints error msg if command wrong
2. Removed e.printStackTrace(); so **won't print command error output.**
> Handling wrong input command

- src/main/java/wallet/logic/command/DeleteCommand.java
- src/main/java/wallet/logic/command/EditCommand.java
- src/main/java/wallet/logic/command/ListCommand.java
- src/main/java/wallet/logic/parser/ContactParserHelper.java
- src/main/java/wallet/logic/parser/DeleteCommandParser.java
- src/main/java/wallet/model/contact/Contact.java
- src/main/java/wallet/model/contact/ContactList.java
- src/main/java/wallet/model/record/Loan.java
- src/main/java/wallet/storage/ContactStorage.java
- src/main/java/wallet/storage/HelpStorage.java
- src/main/java/wallet/ui/Ui.java
- src/main/resources/cmdhistory.txt
- src/main/resources/contact.txt
- src/main/resources/expense.txt
- src/main/resources/general.txt
- src/main/resources/loan.txt
1. Added delete contact feature. Only added codes to @A0171206R 's Loan Class in the end. 
2. Changed commas in help section files to "|" (pipelines) instead for splitting string.
3. Fix for logic error in add and edit contact. 
4. Added table for listing contacts.
> Delete contact 

- src/main/java/wallet/logic/LogicManager.java
- src/main/java/wallet/logic/command/EditCommand.java
- src/main/java/wallet/logic/command/HistoryCommand.java
- src/main/java/wallet/logic/parser/AddCommandParser.java
- src/main/java/wallet/logic/parser/DeleteCommandParser.java
- src/main/java/wallet/logic/parser/DoneCommandParser.java
- src/main/java/wallet/logic/parser/EditCommandParser.java
- src/main/java/wallet/model/record/Loan.java
- src/main/java/wallet/storage/StorageManager.java
- src/main/java/wallet/ui/Ui.java
FIxed: Edit loan date bugs and complexity
Fixed: Command History bugs
> FIxed previous bugs

- build.gradle
- src/main/java/wallet/logic/command/DeleteCommand.java
- src/main/java/wallet/logic/command/EditCommand.java
- src/main/java/wallet/logic/command/ExportCommand.java
- src/main/java/wallet/logic/command/HelpCommand.java
- src/main/java/wallet/logic/command/ImportCommand.java
- src/main/java/wallet/logic/command/ListCommand.java
- src/main/java/wallet/logic/parser/AddCommandParser.java
- src/main/java/wallet/logic/parser/ContactParserHelper.java
- src/main/java/wallet/logic/parser/DeleteCommandParser.java
- src/main/java/wallet/logic/parser/EditCommandParser.java
- src/main/java/wallet/logic/parser/ExportCommandParser.java
- src/main/java/wallet/logic/parser/ImportCommandParser.java
- src/main/java/wallet/logic/parser/ListCommandParser.java
- src/main/java/wallet/logic/parser/ParserManager.java
- src/main/java/wallet/logic/parser/ReminderCommandParser.java
- src/main/java/wallet/logic/parser/ViewCommandParser.java
- src/main/java/wallet/model/contact/Contact.java
- src/main/java/wallet/model/contact/ContactList.java
- src/main/java/wallet/model/record/Loan.java
- src/main/java/wallet/storage/ContactStorage.java
- src/main/java/wallet/storage/HelpStorage.java
- src/main/java/wallet/ui/HelpPrompt.java
- src/main/java/wallet/ui/Ui.java
- src/main/resources/helppaths.txt
1. Only Tested export loans(still buggy)
2. OOP for help
3. Added author tags for reposense
> Export (not completed) and bug fix for != ""

- src/main/java/wallet/logic/command/AddCommand.java
- src/main/java/wallet/logic/command/ListCommand.java
- src/main/java/wallet/logic/command/SetBudgetCommand.java
- src/main/java/wallet/logic/command/ViewCommand.java
- src/main/java/wallet/logic/parser/SetBudgetParser.java
- src/main/java/wallet/logic/parser/ViewCommandParser.java
- src/main/java/wallet/model/record/Budget.java
- src/main/java/wallet/model/record/BudgetList.java
- src/main/java/wallet/model/record/ExpenseList.java
- src/main/java/wallet/storage/BudgetStorage.java
- src/main/java/wallet/thread/ChartThread.java
- src/main/java/wallet/ui/Ui.java
- src/test/java/wallet/logic/command/SetBudgetTest.java
- src/test/java/wallet/logic/command/ViewCommandTest.java
- src/test/java/wallet/logic/parser/SetBudgetParserTest.java
- src/test/java/wallet/logic/parser/ViewCommandParserTest.java
1) Added notifications when new expense exceeds stated budget
2) Ask user if he/she wants to add existing expenses to budget if budget is set after adding expenses
3) Added JUnit Test for the following classes:
a) SetBudgetCommand
b) SetBudgetCommandParser
c) ViewCommand
d) ViewCommandParser
4) Added a few lines for RepoSense
> Notifications (Budget with Expenses)

- src/main/java/wallet/logic/command/ExportCommand.java
- src/main/java/wallet/logic/parser/AddCommandParser.java
- src/main/java/wallet/logic/parser/ContactParserHelper.java
- src/main/java/wallet/logic/parser/EditCommandParser.java
- src/main/java/wallet/logic/parser/ExportCommandParser.java
- src/main/java/wallet/storage/ContactStorage.java
- src/main/java/wallet/ui/Ui.java
1. Basic Export functionality done.
2. Created global variables for error messages.
3. java8 YearMonth function used
> Export Table

- src/main/java/wallet/thread/ChartThread.java
- src/test/java/wallet/logic/command/CurrencyCommandTest.java
> Fixed Pie Chart bug

- src/main/java/wallet/exception/InsufficientParameters.java
- src/main/java/wallet/exception/WrongParameterFormat.java
- src/main/java/wallet/logic/LogicManager.java
- src/main/java/wallet/logic/parser/AddCommandParser.java
- src/main/java/wallet/logic/parser/DeleteCommandParser.java
- src/main/java/wallet/logic/parser/DoneCommandParser.java
- src/main/java/wallet/logic/parser/EditCommandParser.java
- src/main/java/wallet/logic/parser/ExpenseParser.java
- src/main/java/wallet/logic/parser/ParserManager.java
- src/main/java/wallet/ui/Ui.java
Added: New package exception to handle all custom exceptions
Follow the format for adding new custom exceptions for your other components
> Added Custom Exceptions

- src/main/java/wallet/logic/command/ListCommand.java
- src/main/java/wallet/logic/command/ViewCommand.java
- src/main/java/wallet/logic/parser/ParserManager.java
- src/main/java/wallet/logic/parser/SetBudgetParser.java
- src/main/java/wallet/model/record/Category.java
- src/main/java/wallet/model/record/ExpenseList.java
- src/main/java/wallet/model/record/LoanList.java
As per title but includes the following as well:
- Handles exceptions with messages ie. /sortby non-existing sorting word
- Rearranged category to alphabetical order for sorting purposes
- Tested, will complete JUnit Testing later.
- Listall command now works to fix issue highlighted in PE dry run
> Added sorting functions in List

- src/main/java/wallet/logic/command/ExportCommand.java
- src/main/java/wallet/logic/command/ImportCommand.java
- src/main/java/wallet/logic/command/ListCommand.java
- src/main/java/wallet/logic/parser/ExportCommandParser.java
- src/main/java/wallet/logic/parser/ImportCommandParser.java
- src/main/java/wallet/model/contact/ContactList.java
- src/test/java/wallet/logic/parser/AddCommandParserTest.java
- src/test/java/wallet/logic/parser/EditCommandParserTest.java
1. Handled date time exception when user input budget year and month
2. Change import and export commands to "loan" and "expense" 
3. Sort contacts by name (a to z)
4. Exported filename now has the local date and time
> Enhancement to contact and export

- src/main/java/wallet/exception/WrongDateTimeFormat.java
- src/main/java/wallet/logic/LogicManager.java
- src/main/java/wallet/logic/command/AddCommand.java
- src/main/java/wallet/logic/parser/AddCommandParser.java
- src/main/java/wallet/logic/parser/DeleteCommandParser.java
- src/main/java/wallet/storage/StorageManager.java
- src/test/java/wallet/model/record/ExpenseListTest.java
Added more JUnit testing for ExpenseList class.
Added more useful error messages when adding/deleting expenses.
> Added more JUnit testing and error handling

- src/main/java/wallet/logic/command/SetBudgetCommand.java
- src/main/java/wallet/logic/command/ViewCommand.java
- src/main/java/wallet/model/record/BudgetList.java
- src/test/java/wallet/logic/command/SetBudgetTest.java
Budget amount that takes into account of expenses is now separated from set budget.
Set budget is therefore a fixed value now.
No change in commands (Does not affect any existing commands). Only new features are added.
> Fixed amount for budget

- src/main/java/wallet/storage/ExpenseStorage.java
- src/test/java/wallet/logic/command/ViewCommandTest.java
- src/test/java/wallet/logic/parser/DeleteCommandParserTest.java
- src/test/java/wallet/thread/ChartThreadTest.java
Added JUnit test for ViewCommand, ChartThread and DeleteCommandParser.
> More JUnit test

- src/main/java/wallet/thread/ChartThread.java
What the title says.
Previously the pie chart will cut one of its section into 2.
> Fixed PieChart Bug

- src/main/java/wallet/Main.java
- src/main/java/wallet/logic/command/ImportCommand.java
- src/main/java/wallet/logic/command/ListCommand.java
- src/main/java/wallet/logic/parser/AddCommandParser.java
- src/main/java/wallet/logic/parser/ContactParserHelper.java
- src/main/java/wallet/logic/parser/DoneCommandParser.java
- src/main/java/wallet/logic/parser/EditCommandParser.java
- src/main/java/wallet/logic/parser/ExportCommandParser.java
- src/main/java/wallet/logic/parser/ImportCommandParser.java
- src/main/java/wallet/logic/parser/ParserManager.java
- src/main/java/wallet/model/contact/ContactList.java
Things Edited:
1. At ParserManager, try catch for most commands to ensure enough arguments
2. Minor change for importcommand oop
3. Handle not enough arguments for list contact
4. Donecommand parser changed to "loan".equals(arguments[0])
5. Some changes to parsers to allow non case sensitive commands
6. Updated ImportCommandParser to match logic of adding expense in AddCommandParser 
Things need to done:
1. At add and edit parser, have to handle non case sensitive command parameters for expense and loans. (contacts already changed)
2. During import, budget sometimes updates to repeated 9s .999999 . Double subtract has some issues.
> bug fixes and logic errors

- src/main/java/wallet/Main.java
- src/main/java/wallet/logic/LogicManager.java
- src/main/java/wallet/logic/command/EditCommand.java
- src/main/java/wallet/logic/command/ViewCommand.java
- src/main/java/wallet/logic/parser/AddCommandParser.java
- src/main/java/wallet/logic/parser/DeleteCommandParser.java
- src/main/java/wallet/logic/parser/EditCommandParser.java
- src/main/java/wallet/logic/parser/ExpenseParser.java
- src/main/java/wallet/reminder/Reminder.java
- src/main/java/wallet/storage/BudgetStorage.java
- src/main/java/wallet/storage/ContactStorage.java
- src/main/java/wallet/storage/ExpenseStorage.java
- src/main/java/wallet/storage/LoanStorage.java
- src/main/java/wallet/thread/ChartThread.java
- src/main/java/wallet/ui/Ui.java
- src/test/java/wallet/model/record/ExpenseParserTest.java
Added more JUnit test for recurring expenses.
Fix storage error message bug.
Refactor some code.
> Refactor code and fixed storage error messages.

- src/main/java/wallet/logic/command/AddCommand.java
- src/main/java/wallet/logic/command/ImportCommand.java
- src/main/java/wallet/logic/command/ViewCommand.java
- src/main/java/wallet/logic/parser/ExportCommandParser.java
- src/main/java/wallet/model/record/ExpenseList.java
1. Copied Budget codes into Import and Export
2. Fix decimal bug
> Copy Budget codes into Import and Export

- src/main/java/wallet/logic/parser/DoneCommandParser.java
fixed bug for: "done loan 1 2 3 4"
> Minor bug fix

- src/main/java/wallet/logic/parser/ContactParserHelper.java
- src/main/java/wallet/logic/parser/EditCommandParser.java
- src/main/java/wallet/model/contact/Contact.java
- src/test/java/wallet/logic/parser/EditCommandParserTest.java
> Fix edit contact bug
